baseURL = "/"
title = "君往臣 · 个人网站"
languageCode = "zh-cn"
defaultContentLanguage = "en"   # Toha 默认英文，用中文也没问题
#theme = "toha"                  # 有些情况下 Modules 不用写 theme，但写上不影响

disableKinds = ["sitemap"]      # 我们已经验证过，避免权限问题，直接关掉 sitemap

[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"

[params]
  favicon = "images/favicon.ico"   # 以后你可以自己换
  enableBlog = true
  enablePortfolio = true
  enableTimeline = true
  enableContact = true

  [params.author]
    name = "君往臣"
    tagline = "简历 · 博客 · 作品集 · 人生经历"
    avatar = "images/avatar.jpg"   # 之后你放一张头像到 static/images 里即可
